---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: motd
  name: motd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motd
  template:
    metadata:
      labels:
        app: motd
    spec:
      containers:
        - name: motd
          image: blowinginc/motd
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: motd
spec:
  selector:
    app: motd
  ports:
  - protocol: TCP
    port: 8080

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: motd
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
  - hosts:
    - motd.dan.chat
    secretName: letsencrypt-prod
  rules:
  - host: motd.dan.chat
    http:
      paths:
      - path: /
        backend:
          serviceName: motd
          servicePort: 8080